In [1]:
import numpy as np

name = ['Alice', 'Bob', 'Cathy', 'Dodge']
age = [20, 21, 10, 11]
weight = [55.0, 65.0, 32.0, 34.0]

# 生成一个简单数组
# x = np.zeros(4, dtype=int)

# 使用复合数据结构的结构化数组
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [2]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 20, 55.) ('Bob', 21, 65.) ('Cathy', 10, 32.) ('Dodge', 11, 34.)]


In [3]:
# get all names
print(data['name'])
# get first row
print(data[0])
# get the last row's name
print(data[-1]['name'])

['Alice' 'Bob' 'Cathy' 'Dodge']
('Alice', 20, 55.)
Dodge


In [4]:
# Use bool value
data[data['age'] < 18]['name']

array(['Cathy', 'Dodge'], dtype='<U10')

In [5]:
tmp = np.dtype([('id', 'i4'), ('mat', 'f8', (3,3))])
X = np.zeros(1, dtype=tmp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
data['age']

array([20, 21, 10, 11], dtype=int32)

In [7]:
# 记录数组
rec = data.view(np.recarray)
rec.weight

array([55., 65., 32., 34.])

In [8]:
# 记录数组有额外开销
%timeit data['age']
%timeit rec['age']
%timeit rec.age

127 ns ± 5.36 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
3.87 µs ± 583 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.53 µs ± 387 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
